***************
*** 29,38 ****
         vm.o\
  
  # Cross-compiling (e.g., on Mac OS X)
- #TOOLPREFIX = i386-jos-elf-
  
  # Using native tools (e.g., on X86 Linux)
- #TOOLPREFIX = 
  
  # Try to infer the correct TOOLPREFIX if not set
  ifndef TOOLPREFIX
--- 29,38 ----
         vm.o\
  
  # Cross-compiling (e.g., on Mac OS X)
+ TOOLPREFIX = /opt/gnu/i386-jos-elf/bin/
  
  # Using native tools (e.g., on X86 Linux)
+ #TOOLPREFIX =
  
  # Try to infer the correct TOOLPREFIX if not set
  ifndef TOOLPREFIX
***************
*** 51,57 ****
  endif
  
  # If the makefile can't find QEMU, specify its path here
- #QEMU = 
  
  # Try to infer the correct QEMU
  ifndef QEMU
--- 51,57 ----
  endif
  
  # If the makefile can't find QEMU, specify its path here
+ QEMU = qemu-system-i386
  
  # Try to infer the correct QEMU
  ifndef QEMU
